/**
 * GrowthFactorsPanel — Monthly MEF heatmap + seasonal bars + annual growth lines
 * Data source: /data/growth_factors_summary.json (generated by compute_growth_factors.py)
 */
import { useEffect, useState, useMemo } from 'react';
import {
  ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, LineChart, Line, Cell, Legend,
} from 'recharts';
import { TrendingUp, BarChart2, Activity, ArrowUpDown } from 'lucide-react';
import { NEON, REGION_NEON, GlowDefs, Chart3DWrap, TT_NEON, TICK } from '../../lib/chart3d';
import { ModuleNavBar } from '../../shared/ModuleNavBar';

// ─── Types ────────────────────────────────────────────────────────────────────

interface GFMonthly {
  region: string; year: number; month: number; vehicle_class: string;
  mef: number; monthly_aadt: number; annual_aadt: number | null; sample_days: number;
}
interface GFSeasonal {
  region: string; year: number; season: string; vehicle_class: string;
  seasonal_factor: number; seasonal_aadt: number; sample_links: number;
}
interface GFGrowth {
  region: string; vehicle_class: string;
  year_from: number; year_to: number;
  growth_rate: number; cagr: number | null;
  aadt_from: number; aadt_to: number;
}
interface GFTopRoad {
  link_id: string; link_name: string; region: string;
  cagr_total: number; year_from: number; year_to: number;
  aadt_from: number; aadt_to: number;
}
interface GFSummary {
  generated: string;
  year_range: [number, number];
  regions: string[];
  vehicle_classes: string[];
  monthly_factors: GFMonthly[];
  seasonal_factors: GFSeasonal[];
  annual_growth: GFGrowth[];
  top_growing_roads: GFTopRoad[];
}

// ─── Constants ────────────────────────────────────────────────────────────────

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const SEASON_LABELS: Record<string, string> = {
  long_rains:  'Long Rains (Mar–May)',
  dry1:        'Dry Season 1 (Jun–Aug)',
  short_rains: 'Short Rains (Sep–Nov)',
  dry2:        'Dry Season 2 (Dec–Feb)',
};
const SEASON_ORDER = ['long_rains', 'dry1', 'short_rains', 'dry2'];

const VC_LABELS: Record<string, string> = {
  total: 'Total', motorcycle: 'Motorcycles', car: 'Cars/Taxis',
  hgv: 'HGVs', bus: 'Buses', nmt: 'NMT',
};

const VC_COLORS: Record<string, string> = {
  total:      '#6366f1',
  motorcycle: '#00f5ff',
  car:        '#00ff88',
  hgv:        '#ff6b35',
  bus:        '#ffd23f',
  nmt:        '#b967ff',
};

// ─── Colour helpers ───────────────────────────────────────────────────────────

function mefColor(mef: number | undefined): string {
  if (!mef || mef <= 0) return 'rgba(15,15,15,0.6)';
  const dev       = mef - 1.0;
  const intensity = Math.min(1, Math.abs(dev) / 0.20);
  if (dev < 0) {
    return `rgba(0,${Math.round(200 * intensity)},${Math.round(136 * intensity)},${0.15 + intensity * 0.65})`;
  }
  return `rgba(255,${Math.round(107 * (1 - intensity))},${Math.round(53 * (1 - intensity))},${0.15 + intensity * 0.65})`;
}

function mefTextColor(mef: number | undefined): string {
  if (!mef || mef <= 0) return 'rgba(148,163,184,0.3)';
  const dev = mef - 1.0;
  const intensity = Math.min(1, Math.abs(dev) / 0.15);
  if (intensity < 0.3) return 'rgba(148,163,184,0.6)';
  return dev < 0 ? '#00ff88' : '#ff6b35';
}

// ─── Shared styles ────────────────────────────────────────────────────────────

const CARD: React.CSSProperties = {
  background: 'rgba(15,15,15,0.55)',
  backdropFilter: 'blur(20px)',
  border: '1px solid rgba(99,102,241,0.12)',
  borderRadius: 14,
  padding: '16px 20px',
};

const PILL_BASE: React.CSSProperties = {
  fontSize: 10, fontWeight: 700, padding: '3px 10px',
  borderRadius: 6, cursor: 'pointer', border: '1px solid',
  letterSpacing: '0.04em', background: 'transparent', transition: 'all .15s',
};

// ─── Monthly heatmap ─────────────────────────────────────────────────────────

function MonthlyHeatmap({
  data, selectedYear, selectedVC,
}: { data: GFMonthly[]; selectedYear: number; selectedVC: string }) {
  const regions = useMemo(
    () => [...new Set(data.map(d => d.region))].sort(),
    [data],
  );

  const lookup = useMemo(() => {
    const m = new Map<string, GFMonthly>();
    for (const d of data) {
      if (d.year === selectedYear && d.vehicle_class === selectedVC) {
        m.set(`${d.region}|${d.month}`, d);
      }
    }
    return m;
  }, [data, selectedYear, selectedVC]);

  if (!regions.length) {
    return (
      <div style={{ color: 'rgba(148,163,184,0.4)', fontSize: 12, padding: 20, textAlign: 'center' }}>
        No monthly factor data for this selection.
      </div>
    );
  }

  return (
    <div style={{ overflowX: 'auto' }}>
      <table style={{ width: '100%', borderCollapse: 'separate', borderSpacing: 2 }}>
        <thead>
          <tr>
            <th style={{ width: 90, textAlign: 'left', fontSize: 9, color: 'rgba(148,163,184,0.4)', padding: '0 4px 4px', fontWeight: 600 }}>
              Region
            </th>
            {MONTHS.map((m, i) => (
              <th key={m} style={{ fontSize: 9, color: 'rgba(148,163,184,0.45)', fontWeight: 700, padding: '0 0 4px', textAlign: 'center', minWidth: 40 }}>
                {m}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {regions.map(region => (
            <tr key={region}>
              <td style={{ fontSize: 9, color: 'rgba(148,163,184,0.65)', padding: '2px 4px 2px 0', fontWeight: 600, whiteSpace: 'nowrap' }}>
                {region}
              </td>
              {MONTHS.map((_, i) => {
                const month = i + 1;
                const entry = lookup.get(`${region}|${month}`);
                const mef   = entry?.mef;
                return (
                  <td
                    key={month}
                    title={entry ? `MEF ${mef?.toFixed(3)} · ${Math.round(entry.monthly_aadt).toLocaleString()} vpd` : 'No data'}
                    style={{
                      background: mefColor(mef),
                      borderRadius: 4,
                      textAlign: 'center',
                      padding: '5px 2px',
                      fontSize: 8,
                      fontWeight: 800,
                      fontFamily: 'monospace',
                      color: mefTextColor(mef),
                      cursor: 'default',
                      transition: 'opacity .15s',
                    }}
                  >
                    {mef ? mef.toFixed(2) : '—'}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>

      {/* Legend */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 10 }}>
        <span style={{ fontSize: 8, color: 'rgba(148,163,184,0.4)' }}>MEF scale:</span>
        {[
          { color: 'rgba(0,200,136,0.7)', label: '< 0.85 low traffic' },
          { color: 'rgba(0,80,60,0.4)',   label: '0.85–1.0' },
          { color: 'rgba(148,163,184,0.1)', label: '1.0 baseline' },
          { color: 'rgba(255,107,53,0.4)', label: '1.0–1.15' },
          { color: 'rgba(255,40,10,0.7)',  label: '> 1.15 peak' },
        ].map(({ color, label }) => (
          <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
            <div style={{ width: 14, height: 14, background: color, borderRadius: 3 }} />
            <span style={{ fontSize: 7, color: 'rgba(148,163,184,0.5)' }}>{label}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Seasonal bar chart ───────────────────────────────────────────────────────

function SeasonalBars({
  data, regions, selectedYear, selectedVC,
}: { data: GFSeasonal[]; regions: string[]; selectedYear: number; selectedVC: string }) {
  const chartData = useMemo(() => SEASON_ORDER.map(season => {
    const entry: Record<string, unknown> = { season: SEASON_LABELS[season] ?? season };
    for (const region of regions) {
      const rec = data.find(
        d => d.region === region && d.season === season &&
             d.year === selectedYear && d.vehicle_class === selectedVC,
      );
      entry[region] = rec ? +(rec.seasonal_factor).toFixed(4) : null;
    }
    return entry;
  }), [data, regions, selectedYear, selectedVC]);

  const hasData = chartData.some(d => regions.some(r => d[r] != null));
  if (!hasData) {
    return (
      <div style={{ color: 'rgba(148,163,184,0.4)', fontSize: 12, textAlign: 'center', padding: 20 }}>
        No seasonal data for this selection.
      </div>
    );
  }

  const colors = ['#6366f1', '#00f5ff', '#00ff88', '#ff6b35', '#ffd23f', '#b967ff'];

  return (
    <Chart3DWrap>
      <ResponsiveContainer width="100%" height={230}>
        <BarChart data={chartData} margin={{ top: 4, right: 10, left: 0, bottom: 40 }}>
          <GlowDefs id="seasonal" />
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.06)" />
          <XAxis dataKey="season" tick={{ ...TICK, fontSize: 8 }} axisLine={false} tickLine={false}
            angle={-20} textAnchor="end" interval={0} />
          <YAxis tick={TICK} axisLine={false} tickLine={false} width={38}
            tickFormatter={(v: number) => v.toFixed(2)} />
          <Tooltip
            {...TT_NEON}
            formatter={(v: number, name: string) => [
              v ? `×${v.toFixed(3)}` : 'N/A',
              name,
            ]}
          />
          <Legend wrapperStyle={{ fontSize: 9, color: 'rgba(148,163,184,0.6)', paddingTop: 4 }} />
          {regions.map((region, i) => (
            <Bar key={region} dataKey={region as string} fill={colors[i % colors.length]}
              radius={[3, 3, 0, 0]} maxBarSize={24} animationDuration={800}
              fillOpacity={0.82} />
          ))}
        </BarChart>
      </ResponsiveContainer>
    </Chart3DWrap>
  );
}

// ─── Annual growth line chart ─────────────────────────────────────────────────

function AnnualGrowthChart({
  data, selectedRegion, vcList,
}: { data: GFGrowth[]; selectedRegion: string; vcList: string[] }) {
  const filtered = useMemo(
    () => data.filter(d =>
      (selectedRegion === 'all' || d.region === selectedRegion) &&
      vcList.includes(d.vehicle_class),
    ),
    [data, selectedRegion, vcList],
  );

  // Build year-pairs present in data
  const pairs = useMemo(() => {
    const set = new Set<string>();
    filtered.forEach(d => set.add(`${d.year_from}→${d.year_to}`));
    return [...set].sort();
  }, [filtered]);

  const chartData = useMemo(() => pairs.map(pair => {
    const [yf, yt] = pair.split('→').map(Number);
    const entry: Record<string, unknown> = { period: pair };
    for (const vc of vcList) {
      const recs = filtered.filter(d => d.vehicle_class === vc && d.year_from === yf && d.year_to === yt);
      if (recs.length) {
        const avgRate = recs.reduce((s, r) => s + r.growth_rate, 0) / recs.length;
        entry[vc] = +(avgRate * 100).toFixed(2);
      }
    }
    return entry;
  }), [pairs, filtered, vcList]);

  if (!chartData.length) {
    return (
      <div style={{ color: 'rgba(148,163,184,0.4)', fontSize: 12, textAlign: 'center', padding: 20 }}>
        No annual growth data for this selection.
      </div>
    );
  }

  return (
    <Chart3DWrap>
      <ResponsiveContainer width="100%" height={240}>
        <LineChart data={chartData} margin={{ top: 4, right: 20, left: 0, bottom: 0 }}>
          <GlowDefs id="growth" />
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.06)" />
          <XAxis dataKey="period" tick={{ ...TICK, fontSize: 8 }} axisLine={false} tickLine={false} />
          <YAxis tick={TICK} axisLine={false} tickLine={false} width={44}
            tickFormatter={(v: number) => `${v > 0 ? '+' : ''}${v.toFixed(0)}%`} />
          <Tooltip
            {...TT_NEON}
            formatter={(v: number, name: string) => [
              `${v > 0 ? '+' : ''}${v.toFixed(2)}%`,
              VC_LABELS[name] ?? name,
            ]}
          />
          <Legend
            formatter={(value: string) => VC_LABELS[value] ?? value}
            wrapperStyle={{ fontSize: 9, color: 'rgba(148,163,184,0.6)' }}
          />
          {vcList.map(vc => (
            <Line
              key={vc}
              type="monotone"
              dataKey={vc}
              stroke={VC_COLORS[vc] ?? '#94a3b8'}
              strokeWidth={2}
              dot={{ fill: VC_COLORS[vc] ?? '#94a3b8', r: 4 }}
              connectNulls
              animationDuration={900}
            />
          ))}
        </LineChart>
      </ResponsiveContainer>
    </Chart3DWrap>
  );
}

// ─── Top growing roads table ──────────────────────────────────────────────────

type SortKey = 'cagr_total' | 'link_name' | 'region' | 'year_from';

function TopRoadsTable({ data }: { data: GFTopRoad[] }) {
  const [sortKey,  setSortKey]  = useState<SortKey>('cagr_total');
  const [sortDesc, setSortDesc] = useState(true);

  function toggleSort(k: SortKey) {
    if (k === sortKey) setSortDesc(d => !d);
    else { setSortKey(k); setSortDesc(true); }
  }

  const sorted = useMemo(() => [...data].sort((a, b) => {
    const av = a[sortKey], bv = b[sortKey];
    if (typeof av === 'number' && typeof bv === 'number')
      return sortDesc ? bv - av : av - bv;
    const as = String(av ?? ''), bs = String(bv ?? '');
    return sortDesc ? bs.localeCompare(as) : as.localeCompare(bs);
  }), [data, sortKey, sortDesc]);

  const Th = ({ label, k }: { label: string; k: SortKey }) => (
    <th
      onClick={() => toggleSort(k)}
      style={{
        padding: '6px 10px', textAlign: 'left', fontSize: 9,
        fontWeight: 700, color: sortKey === k ? '#6366f1' : 'rgba(148,163,184,0.45)',
        textTransform: 'uppercase', letterSpacing: '0.08em',
        cursor: 'pointer', userSelect: 'none', borderBottom: '1px solid rgba(99,102,241,0.1)',
        whiteSpace: 'nowrap',
      }}
    >
      {label} {sortKey === k ? (sortDesc ? '▼' : '▲') : ''}
    </th>
  );

  if (!sorted.length) {
    return (
      <div style={{ color: 'rgba(148,163,184,0.4)', fontSize: 12, textAlign: 'center', padding: 20 }}>
        No road-level growth data available.
      </div>
    );
  }

  return (
    <div style={{ overflowX: 'auto', maxHeight: 340, overflowY: 'auto' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
        <thead style={{ position: 'sticky', top: 0, background: 'rgba(10,15,30,0.95)' }}>
          <tr>
            <Th label="Road / Link" k="link_name" />
            <Th label="Region"      k="region" />
            <Th label="CAGR"        k="cagr_total" />
            <Th label="Base Year"   k="year_from" />
            <th style={{ padding: '6px 10px', fontSize: 9, color: 'rgba(148,163,184,0.45)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', borderBottom: '1px solid rgba(99,102,241,0.1)' }}>AADT Trend</th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((road, i) => {
            const pct     = road.cagr_total * 100;
            const isPos   = pct >= 0;
            const color   = isPos ? '#00ff88' : '#ff6b35';
            const absCAGR = Math.abs(pct);
            return (
              <tr key={`${road.link_id}-${i}`}
                style={{ borderBottom: '1px solid rgba(148,163,184,0.05)' }}
                className="hover:bg-slate-800/40">
                <td style={{ padding: '7px 10px', color: '#e2eaf4', maxWidth: 220 }}>
                  <div style={{ fontWeight: 600, fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {road.link_name}
                  </div>
                  <div style={{ fontSize: 9, color: 'rgba(148,163,184,0.4)', fontFamily: 'monospace' }}>
                    {road.link_id}
                  </div>
                </td>
                <td style={{ padding: '7px 10px', color: REGION_NEON[road.region] ?? '#64748b', fontSize: 11 }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                    <span style={{ width: 6, height: 6, borderRadius: '50%', background: REGION_NEON[road.region] ?? '#64748b', flexShrink: 0 }} />
                    {road.region}
                  </span>
                </td>
                <td style={{ padding: '7px 10px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span style={{ fontSize: 13, fontWeight: 900, color, fontFamily: 'monospace', minWidth: 56 }}>
                      {isPos ? '+' : ''}{pct.toFixed(1)}%
                    </span>
                    <div style={{ flex: 1, height: 5, background: 'rgba(148,163,184,0.06)', borderRadius: 3, overflow: 'hidden', minWidth: 40 }}>
                      <div style={{ height: '100%', width: `${Math.min(100, absCAGR / 0.30 * 100)}%`, background: color, borderRadius: 3 }} />
                    </div>
                  </div>
                </td>
                <td style={{ padding: '7px 10px', color: 'rgba(148,163,184,0.5)', fontSize: 10, fontFamily: 'monospace' }}>
                  {road.year_from}→{road.year_to}
                </td>
                <td style={{ padding: '7px 10px', fontSize: 9, color: 'rgba(148,163,184,0.45)', fontFamily: 'monospace' }}>
                  {Math.round(road.aadt_from).toLocaleString()} → {Math.round(road.aadt_to).toLocaleString()} vpd
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ─── Main export ──────────────────────────────────────────────────────────────

export default function GrowthFactorsPanel() {
  const [data,           setData]           = useState<GFSummary | null>(null);
  const [loading,        setLoading]        = useState(true);
  const [selectedRegion, setSelectedRegion] = useState<string>('all');
  const [selectedVC,     setSelectedVC]     = useState<string>('total');
  const [selectedYear,   setSelectedYear]   = useState<number>(2023);

  useEffect(() => {
    const base = import.meta.env.BASE_URL;
    fetch(`${base}data/growth_factors_summary.json`)
      .then(r => r.json())
      .then((d: GFSummary) => {
        setData(d);
        if (d.year_range?.[1]) setSelectedYear(d.year_range[1]);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const visibleRegions = useMemo(() => {
    if (!data) return [];
    return selectedRegion === 'all'
      ? data.regions.filter(r => r !== 'Unknown')
      : [selectedRegion];
  }, [data, selectedRegion]);

  const filteredMonthly = useMemo(
    () => (data?.monthly_factors ?? []).filter(d =>
      selectedRegion === 'all' ? d.region !== 'Unknown' : d.region === selectedRegion,
    ),
    [data, selectedRegion],
  );

  const availableYears = useMemo(() => {
    if (!data) return [];
    return [...new Set(data.monthly_factors.map(d => d.year))].sort();
  }, [data]);

  const vcList = useMemo(() => {
    if (!data) return ['total'];
    return data.vehicle_classes.filter(vc => vc !== 'nmt');
  }, [data]);

  if (loading) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center',
        height: '100%', background: '#0a0f1e',
        color: 'rgba(148,163,184,0.4)', fontSize: 13, fontFamily: "'Inter','Segoe UI',sans-serif" }}>
        Computing growth factors…
      </div>
    );
  }

  if (!data) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center',
        height: '100%', background: '#0a0f1e',
        color: 'rgba(148,163,184,0.35)', fontSize: 13, fontFamily: "'Inter','Segoe UI',sans-serif" }}>
        Run <code style={{ marginLeft: 6, color: '#6366f1' }}>python scripts/compute_growth_factors.py</code>&nbsp;to generate data.
      </div>
    );
  }

  const generatedDate = data.generated
    ? new Date(data.generated).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
    : '';

  return (
    <div className="flex-1 overflow-y-auto p-5 space-y-5 animate-fade-in"
      style={{ fontFamily: "'Inter','Segoe UI',sans-serif", background: '#0a0f1e' }}>
      <ModuleNavBar module="TIS" />

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
        <div style={{ width: 40, height: 40, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center',
          background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)' }}>
          <TrendingUp size={20} style={{ color: '#6366f1' }} />
        </div>
        <div>
          <h1 style={{ fontSize: 18, fontWeight: 800, color: '#fff', margin: 0 }}>Growth Factors</h1>
          <p style={{ fontSize: 11, color: 'rgba(148,163,184,0.5)', margin: 0 }}>
            Monthly expansion, seasonal variation & annual growth · {data.year_range[0]}–{data.year_range[1]}
            {generatedDate && <span style={{ marginLeft: 6 }}>· generated {generatedDate}</span>}
          </p>
        </div>

        {/* Filters */}
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
          {/* Region */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <span style={{ fontSize: 9, fontWeight: 700, color: 'rgba(148,163,184,0.4)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Region</span>
            <select value={selectedRegion} onChange={e => setSelectedRegion(e.target.value)}
              style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.25)',
                borderRadius: 7, color: '#e2eaf4', fontSize: 11, fontWeight: 600,
                padding: '3px 8px', cursor: 'pointer', outline: 'none', fontFamily: 'inherit' }}>
              <option value="all">All Regions</option>
              {data.regions.map(r => <option key={r} value={r}>{r}</option>)}
            </select>
          </div>

          {/* Vehicle class */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <span style={{ fontSize: 9, fontWeight: 700, color: 'rgba(148,163,184,0.4)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Class</span>
            <select value={selectedVC} onChange={e => setSelectedVC(e.target.value)}
              style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.25)',
                borderRadius: 7, color: '#e2eaf4', fontSize: 11, fontWeight: 600,
                padding: '3px 8px', cursor: 'pointer', outline: 'none', fontFamily: 'inherit' }}>
              {data.vehicle_classes.map(vc => (
                <option key={vc} value={vc}>{VC_LABELS[vc] ?? vc}</option>
              ))}
            </select>
          </div>

          {/* Year */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <span style={{ fontSize: 9, fontWeight: 700, color: 'rgba(148,163,184,0.4)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Year</span>
            <select value={selectedYear} onChange={e => setSelectedYear(Number(e.target.value))}
              style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.25)',
                borderRadius: 7, color: '#e2eaf4', fontSize: 11, fontWeight: 600,
                padding: '3px 8px', cursor: 'pointer', outline: 'none', fontFamily: 'inherit' }}>
              {availableYears.map(y => <option key={y} value={y}>{y}</option>)}
            </select>
          </div>
        </div>
      </div>

      {/* ── KPI chips ──────────────────────────────────────────────────────── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 12 }}>
        {[
          {
            label: 'Links Analysed',
            value: [...new Set(data.top_growing_roads.map(r => r.link_id))].length.toLocaleString(),
            sub: 'with multi-year data', color: '#6366f1',
          },
          {
            label: 'Year Range',
            value: `${data.year_range[0]}–${data.year_range[1]}`,
            sub: 'survey years', color: '#00f5ff',
          },
          {
            label: 'Regions',
            value: String(data.regions.filter(r => r !== 'Unknown').length),
            sub: 'Department of National Roads maintenance regions', color: '#00ff88',
          },
          {
            label: 'Vehicle Classes',
            value: String(data.vehicle_classes.length),
            sub: 'incl. NMT', color: '#ffd23f',
          },
        ].map(kpi => (
          <div key={kpi.label} style={{ ...CARD, borderColor: `${kpi.color}22` }}>
            <div style={{ fontSize: 22, fontWeight: 900, color: kpi.color, lineHeight: 1,
              textShadow: `0 0 18px ${kpi.color}44` }}>{kpi.value}</div>
            <div style={{ fontSize: 11, fontWeight: 700, color: '#e2eaf4', marginTop: 4 }}>{kpi.label}</div>
            <div style={{ fontSize: 9, color: 'rgba(148,163,184,0.45)', marginTop: 2 }}>{kpi.sub}</div>
          </div>
        ))}
      </div>

      {/* ── Monthly MEF heatmap ─────────────────────────────────────────────── */}
      <div style={CARD}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
          <Activity size={14} style={{ color: '#6366f1' }} />
          <div>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#fff' }}>
              Monthly Expansion Factors (MEF) — {selectedYear}
            </div>
            <div style={{ fontSize: 10, color: 'rgba(148,163,184,0.45)' }}>
              Monthly AADT ÷ Annual AADT · &gt;1.0 = peak · &lt;1.0 = trough
            </div>
          </div>
        </div>
        <MonthlyHeatmap
          data={filteredMonthly}
          selectedYear={selectedYear}
          selectedVC={selectedVC}
        />
      </div>

      {/* ── Seasonal factors ────────────────────────────────────────────────── */}
      <div style={CARD}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
          <BarChart2 size={14} style={{ color: '#00f5ff' }} />
          <div>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#fff' }}>
              Seasonal Factors by Region — {selectedYear}
            </div>
            <div style={{ fontSize: 10, color: 'rgba(148,163,184,0.45)' }}>
              Uganda seasons: Long Rains (Mar–May) · Dry 1 (Jun–Aug) · Short Rains (Sep–Nov) · Dry 2 (Dec–Feb)
            </div>
          </div>
        </div>
        <SeasonalBars
          data={data.seasonal_factors}
          regions={visibleRegions.slice(0, 5)}
          selectedYear={selectedYear}
          selectedVC={selectedVC}
        />
      </div>

      {/* ── Annual growth line chart ─────────────────────────────────────────── */}
      <div style={CARD}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
          <TrendingUp size={14} style={{ color: '#00ff88' }} />
          <div>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#fff' }}>
              Year-on-Year Growth Rate
              {selectedRegion !== 'all' ? ` · ${selectedRegion}` : ' · All Regions'}
            </div>
            <div style={{ fontSize: 10, color: 'rgba(148,163,184,0.45)' }}>
              Annual growth rate % per vehicle class between consecutive survey years
            </div>
          </div>
        </div>
        <AnnualGrowthChart
          data={data.annual_growth}
          selectedRegion={selectedRegion}
          vcList={vcList}
        />
      </div>

      {/* ── Top growing roads ────────────────────────────────────────────────── */}
      <div style={CARD}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
          <ArrowUpDown size={14} style={{ color: '#ffd23f' }} />
          <div>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#fff' }}>
              Top Growing Roads — by CAGR (Total Traffic)
            </div>
            <div style={{ fontSize: 10, color: 'rgba(148,163,184,0.45)' }}>
              Links with ≥2 years data and ≥5 survey days · sorted by compound annual growth rate
            </div>
          </div>
        </div>
        <TopRoadsTable data={data.top_growing_roads} />
      </div>

      {/* ── Footer note ──────────────────────────────────────────────────────── */}
      <div style={{ fontSize: 9, color: 'rgba(148,163,184,0.25)', paddingBottom: 8 }}>
        Sources: Department of National Roads Traffic Information System (TIS) annual surveys · ATC permanent counters ·
        Computed from traffic_platform.db via compute_growth_factors.py
      </div>
    </div>
  );
}
